### ISSUE TITLE
Helm repo not available?

### ISSUE THREAD

**Issue by PatrickSplice** [ObjectifLibre/kube-oidc#1]
Tried adding the helm repo and it is failing:

[centos@k8s-master kube-oidc]$ helm repo add fydrahcharts https://charts.fhardy.fr
Error: Looks like "https://charts.fhardy.fr" is not a valid chart repository or cannot be reached: Failed to fetch https://charts.fhardy.fr/index.yaml : 404 Not Found

**Comment by fydrah** [comment]
Hi @PatrickSplice,

Helm repository has been migrated:

```
helm repo add fhardy-stable https://registry.fhardy.fr/chartrepo/stable
helm repo update
helm fetch fhardy-stable/kube-oidc
```
This is a lake of documentation, I will fix this soon.
