### ISSUE TITLE
Helm repo timeout

### ISSUE THREAD

**Issue by lossanarch** [ObjectifLibre/kube-oidc#2]
Hi @fydrah 

The new repo at registry.fhardy.fr/chartrepo/stable also appears to be timing out now, getting:

```
...Unable to get an update from the "fhardy-stable" chart repository (https://registry.fhardy.fr/chartrepo/stable):
	Get https://registry.fhardy.fr/chartrepo/stable/index.yaml: dial tcp 195.154.156.211:443: connect: operation timed out
```

Thanks for this chart, it's very handy.

**Comment by fydrah** [comment]
Hi @lossanarch ,

It seems it's working now:
```
~ $ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "fhardy-stable" chart repository
/tmp $ helm fetch fhardy-stable/kube-oidc
/tmp $ ls
kube-oidc-1.0.0.tgz
```
Did you tried again ?

I recently upgrade the repository, this could be a side effect.

**Comment by lucasvilelarodrigues** [comment]
@fydrah 
The repo appears to be Unavailable again.

`$ helm repo add fhardy-stable https://registry.fhardy.fr/chartrepo/stable
Error: Looks like "https://registry.fhardy.fr/chartrepo/stable" is not a valid chart repository or cannot be reached: Failed to fetch https://registry.fhardy.fr/chartrepo/stable/index.yaml : 503 Service Unavailable
`

Could you check please? This repo helps a lot! 
Thanks

**Comment by fydrah** [comment]
Hi @lucasvilelarodrigues ,
chart repo crashed due to a failed harbor upgrade. Everything works now.

**Comment by lucasvilelarodrigues** [comment]
Thanks @fydrah , now its work fine!
